baseURL = "https://aditaja.my.id/"

# include content marked as draft
buildDrafts = false

# include content with publishdate in the future
buildFuture = false

# include content already expired
buildExpired = false

# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "vim"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "· Aditya Rahman ·"
googleAnalytics = "G-VN1QN22GSV"
disableKinds = ["taxonomy", "term"]

[permalinks]
  fixed = ":title/"

[params]
  author = "Aditya Rahman"
  email = "mail@aditaja.my.id"
  description = "Aditya Rahman, DevOps Engineer, Indonesia"
  bio = "DevOps Engineer  \nIndonesia"
  avatar = "img/photo-profile.webp"
  favicon = "img/favicon.ico"

  [params.contact]
    leanpub = "https://blog.aditaja.my.id/"
    github = "https://github.com/kudaliar032"
    gitlab = "https://gitlab.com/kudaliar032"
    instagram = "https://instagram.com/kudaliar032"
    twitter = "https://twitter.com/kudaliar032"
    facebook = "https://facebook.com/kudaliar032"
    linkedin = "https://www.linkedin.com/in/adityarahman032"
